### ISSUE TITLE
pass-authz-tools seems to ignore pass.fedora.baseurl

### ISSUE THREAD

**Issue by derekbelrose** [eclipse-pass/pass-authz#82]
I'm running pass-authz-tools-0.2.1-SNAPSHOT-container-permissions-exe.jar on a new fcrepo with the following:

java -Dpass.fedora.baseurl=http://fcrepo-test.pass.local:8080/fcrepo/rest/ -Dpass.fedora.user=fedoraAdmin -Dpass.fedora.password=xxxxxx -jar pass-authz-tools-0.2.1-SNAPSHOT-container-permissions-exe.jar

and it's coming back with the following error:

Setting permissions of http://localhost:8080/fcrepo/rest/
      read:  [http://oapass.org/ns/roles/johnshopkins.edu#submitter, http://oapass.org/ns/roles/johnshopkins.edu#pass-backend, http://oapass.org/ns/roles/johnshopkins.edu#admin]
    append:  []
     write:  []
Exception in thread "main" java.lang.RuntimeException: Error communicating with repository
        at org.dataconservancy.pass.authz.acl.ACLManager$Builder.perform(ACLManager.java:271)
        at org.dataconservancy.pass.authz.tools.main.ContainerPermissions.main(ContainerPermissions.java:87)
Caused by: org.fcrepo.client.FcrepoOperationFailedException: HTTP operation failed invoking http://localhost:8080/fcrepo/rest/ with statusCode: -1 and message: Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
        at org.fcrepo.client.FcrepoClient.executeRequest(FcrepoClient.java:219)
        at org.fcrepo.client.FcrepoClient.executeRequest(FcrepoClient.java:205)
        at org.fcrepo.client.RequestBuilder.perform(RequestBuilder.java:78)
        at org.dataconservancy.pass.authz.acl.ACLManager$Builder.findOrCreateACL(ACLManager.java:287)
        at org.dataconservancy.pass.authz.acl.ACLManager$Builder.perform(ACLManager.java:263)
        ... 1 more

According to the documentation for both the pass-authz-tools and the Java Fedora client, I should be able to set pass.fcrepo.baseurl.

**Comment by rpoet-jh** [comment]
The migration of PASS repositories to eclipse-pass is complete.  This issue is no longer relevant and is being closed as part of archiving https://github.com/eclipse-pass/main/issues/585.
